on:
  workflow_call:
    inputs:
      stage:
        type: number
        required: true

env:
  REPO: /home/runner/apt_repo
  AGG: /home/runner/apt_repo_dependencies

jobs:
  aggregate:
    runs-on: ubuntu-24.04-arm
    env:
      stage: stage${{ inputs.stage }}
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          echo "previous_stage=stage$((${{ inputs.stage }}-1))" >> $GITHUB_ENV
          mkdir -p ${{ env.AGG }}
      - name: Fetch results of previous stage
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.AGG }}
          key: apt-repo-${{ env.previous_stage }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            apt-repo-${{ env.previous_stage }}-${{ github.sha }}-${{ github.run_id }}
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker0
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker1
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker2
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker3
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker4
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker5
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker6
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker7
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker8
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker9
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker10
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker11
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker12
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker13
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker14
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker15
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker16
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker17
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker18
      - name: Aggregate worker
        uses: ./.github/actions/aggregate-worker
        with:
          worker: ${{ env.stage }}-worker19
      - name: Store apt repo
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ env.AGG }}
          key: apt-repo-${{ env.stage }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
